// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig, env } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
    seed: "prisma/seed.ts",
  },
  datasource: {
    // Migrate / db push need a direct Postgres session. Supabase transaction pooler (:6543)
    // triggers "prepared statement \"s1\" already exists". Use DIRECT_URL (see Supabase dashboard).
    url: process.env["DIRECT_URL"] ?? env("DATABASE_URL"),
  },
});
